### ISSUE TITLE
Unit Rates master checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#1]
# Unit Rates master checklist
## Design
- [x] **Sim folder and design doc created** (Date: 09/22/2015) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Learning goals and standards identified** (Date: 12/08/2015)
- [x] **Design concept complete**  (Date: 01/19/2016)
- [x] **Wireframes complete** (Date: 02/18/2016) 
- [x] **Mockups complete** (Date: 07/21/2016) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Interviews complete** (Date: 03/10/2017) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 03/13/2017) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide
  - [x] Add an activity  (Karina H. is working on this.)
<s>Sim primer</s>  -- Being tracked in #197
  - [x] Verify credits
- [x] **Add to Edmodo**
- [x] **Add to [Gooru](http://gooru.org/PhET/content/resources)** (signed in as phethelp)

## Implementation
- [X] **Sim repo created** (Date: 02/18/2016) 
  - [x] Simula-rasa used to create basic project structure
  - [x] Grunt unpublished-readme run to create the initial readme file
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] Standard label set applied
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
- [x] **Initial development started** (Date: 03/14/2016)
- [x] **Sim feature complete** (Date: 03/05/2017) 
- [x] **Code review complete** (Date: 03/13/2017) 
  - [x] Code review checklist
  - [x] Model description 
- [x] **Published** (Date: 4/4/2017) 
  - [x] Update repo README to published template
## QA
- [x] **Dev testing complete** (Date: 3/13/17) 
- [x] **First release candidate** (Date: 4/3/17)
  - [x] Place matrix in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
  - [x] Test matrix deemed complete

**Comment by pixelzoom** [comment]
@arouinfar Please review the check list to see if there's anything that can be checked off. 

I don't know when "initial development" started, so please fill that in if you have even a rough idea.

**Comment by arouinfar** [comment]
Will do @pixelzoom.

**Comment by arouinfar** [comment]
Found a status report from DS from 3/16/16 that says he began work on the Shopping screen, so I'll use 3/14/16 (previous Monday) as the rough start date for implementation.

**Comment by pixelzoom** [comment]
@amanda-phet Please complete the "Mockups", "Interviews" and "Lead Designer" sections of the checklist.

**Comment by arouinfar** [comment]
@pixelzoom I'll be taking care of that.

**Comment by arouinfar** [comment]
@ariel-phet can you take care of the Master Doc List and Gooru spreadsheet? The linked Master Doc List is deprecated, and the redirect link doesn't seem appropriate. 

I've added the description, learning goals, keywords, etc. to the [Website Info](https://docs.google.com/document/d/104G3PEWgGGMw3PKWQPAMX67SL79kXoF4Bun6GTUDiUo/edit#heading=h.mv3glozfezqu) section of the design doc. @amanda-phet if you're feeling up to it, can you please review?  In particular, can you look at the description and learning goals? I have them written, but I've highlighted two places where I'm unsure of the wording choice.

**Comment by pixelzoom** [comment]
If there are bits of the checklist that are incorrect/obsolete, it's probably because the checklist has evolved.  For the latest checklist, see https://github.com/phetsims/phet-info/blob/master/checklists/sim_new_checklist.md.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I'll compare this checklist to the one you've linked, and update as necessary.

**Comment by amanda-phet** [comment]
Looks good, I just added a few keywords and added some suggestions for the wording of the learning goals.

**Comment by arouinfar** [comment]
Thanks @amanda-phet!!

**Comment by ariel-phet** [comment]
@arouinfar will take care of gooru and edmodo once live on webiste

**Comment by arouinfar** [comment]
@pixelzoom @ariel-phet I've made the sim visible. I'll work on getting the Teacher Tips uploaded and the rest of the checklist completed later today or tomorrow.

@pixelzoom are there any 3rd party libraries we'll need to credit on the sim page? I didn't see any mention of Unit Rates on https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md

**Comment by pixelzoom** [comment]
Whoops, I didn't update https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md.  Just did it now.   I'm not clear on when 3rd-party libs need to be credited on the sim's webpage, so please take a look.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! I'm modeling the 3rd party credits after Gravity and Orbits
https://phet.colorado.edu/en/simulation/gravity-and-orbits#credits

I will add the relevant libraries to the sim page credits.

**Comment by arouinfar** [comment]
Nevermind... looks like that field has already been populated. Thanks again @pixelzoom!

**Comment by pixelzoom** [comment]
According to @mattpen, running "grunt report-third-party" does 2 things:  It regenerates [third-party-licenses.md](https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md).  And it updates the information in the website database, which is what is displayed under Credits on the sim's webpage.

**Comment by arouinfar** [comment]
Good to know @pixelzoom!

**Comment by ariel-phet** [comment]
@arouinfar looks like the final items on here are yours

**Comment by pixelzoom** [comment]
@arouinfar can you move any remaining tasks to individual issues, then close this issue?

**Comment by pixelzoom** [comment]
@arouinfar ping.

**Comment by pixelzoom** [comment]
@arouinfar ping.  This has been high priority since Apr 3.
